version: 0.0
os: linux

files:
  - source: build/deploy/identityiq.war
    destination: /usr/bin/spBuild/opt/tomcat/webapps
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/remove_old_war.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy_war.sh
      timeout: 1800
      runas: root

  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/run-selenium.sh
      timeout: 900
      runas: root

