version: 0.0
os: linux

files:
  - source: build/deploy/identityiq.war
    destination: /usr/bin/spBuild/opt/tomcat/webapps

hooks:
  BeforeInstall:
    - location: scripts/remove_old_war.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 300
      runas: root
