version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies"
      - yum install -y ant bsf bsh unzip zip dos2unix
      - echo "Ant binary:"
      - which ant
      - echo "Detecting ANT_HOME"
      - export ANT_HOME=$(rpm -ql ant | grep '/lib/ant-launcher.jar$' | sed 's#/lib/ant-launcher.jar##')
      - export PATH=$PATH:$ANT_HOME/bin
      - echo "ANT_HOME=$ANT_HOME"
      - ls -l $ANT_HOME/lib | head
      - ant -version

  pre_build:
    commands:
      - echo "Preparing IdentityIQ build"
      - chmod +x build.sh
      - echo "Downloading IdentityIQ GA package"
      - aws s3 cp s3://download-local/identityiq-8.5.zip base/ga/
      - ls -l base/ga

  build:
    commands:
      - echo "Running IdentityIQ build"
      - export SPTARGET=dev
      - ./build.sh war
      - echo "Listing deploy artifacts"
      - ls -l build/deploy

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/deploy/**/*
